// NedZL images

export { default as NEDZL_LOGO_WHITE } from "../assets/images/nedzl-logo-white.svg";
export { default as NEDZL_LOGO_GREEN } from "../assets/images/nedzl-logo-green.svg";
export { default as NEDZL_AUTH_LAYOUT } from "../assets/images/auth_layout.png";
export { default as PAD_LOCK } from "../assets/icons/padlock.svg";
export { default as CHECK_GREEN } from "../assets/images/check-green.svg";
export { default as USER } from "../assets/images/user_.svg";
export { default as HELP } from "../assets/images/help.svg";
export { default as NIGERIA_FLAG } from "../assets/images/flag-nigeria.svg";
export { default as SEARCH_INPUT } from "../assets/icons/search 1 (1).svg";
export { default as BAR_WHITE } from "../assets/images/bar-white.svg";
export { default as FACEBOOK } from "../assets/images/facebook.svg";
export { default as TWITTER } from "../assets/images/twitter.svg";
export { default as DISCORD } from "../assets/images/ic_sharp-discord.svg";
export { default as INSTAGRAM } from "../assets/images/basil_instagram-solid.svg";
export { default as LEXUS } from "../assets/images/lexus.jpg";
export { default as GRAY_PLAY } from "../assets/icons/gray-play.svg";
export { default as LOCATION } from "../assets/images/location.svg";
export { default as OUTLINE_EYE } from "../assets/icons/outline-eye.svg";
export { default as OUTLINE_LOCATION } from "../assets/icons/outline-location.svg";
export { default as HEART } from "../assets/icons/heart.svg";
export { default as SHARE } from "../assets/icons/share.svg";
export { default as PROFILE } from "../assets/images/profile.png";
export { default as VERIFIED } from "../assets/images/verified.svg";
export { default as SINGLE_USER } from "../assets/images/singe-user.svg";
export { default as SINGLE_USER_WHITE } from "../assets/images/single-user-white.svg";
export { default as REVIEW_BLACK } from "../assets/images/review-black.svg";
export { default as REVIEW_WHITE } from "../assets/images/review-white.svg";
export { default as REVIEWS_BLACK } from "../assets/images/reviews-black.svg";
export { default as REVIEWS_WHITE } from "../assets/images/reviews-white.svg";
export { default as STORE_SETTINGS_BLACK } from "../assets/images/store-settings-black.svg";
export { default as STORE_SETTINGS_WHITE } from "../assets/images/store-settings-white.svg";
export { default as INBOX_BLACK } from "../assets/images/inbox-black.svg";
export { default as INBOX_WHITE } from "../assets/images/inbox-white.svg";
export { default as SETTINGS_BLACK } from "../assets/images/settings-black.svg";
export { default as SETTINGS_WHITE } from "../assets/images/settings-white.svg";
export { default as ADS_WHITE } from "../assets/images/ads-white.svg";
export { default as ADS_BLACK } from "../assets/images/ads-black.svg";
export { default as SINGLE_USER_BLACK } from "../assets/images/single_user_black.svg";
export { default as GREEN_USER } from "../assets/images/green-user.svg";
export { default as EDIT_PROFILE } from "../assets/images/edit-profile.svg";
export { default as LOG_OUT_RED } from "../assets/images/logout-red.svg";
export { default as ART_WORK } from "../assets/images/Artwork.svg";
export { default as ARROW_BACK } from "../assets/images/eva_arrow-back-fill.svg";
export { default as INFO_RED } from "../assets/images/info-red.svg";
export { default as UPLOAD } from "../assets/images/upload.svg";
export { default as PRELOADER_ICON } from "../assets/images/preloader-icon.svg";
export { default as CALENDER_GREEN } from "../assets/icons/calender-green.svg";
export { default as CLOCK_GREEN } from "../assets/icons/clock-green.svg";
export { default as DOUBLE_DIRECT } from "../assets/images/double-direct.svg";
export { default as ARROW_DOWN } from "../assets/icons/arrow-down.svg";
export { default as LINE } from "../assets/images/Line 1.svg";

// end
export { default as FEND_LOGO } from "../assets/images/fend-logo.svg";
export { default as SHOPPING_BAG } from "../assets/images/shopping-basket.svg";
export { default as BOXES } from "../assets/images/boxes.svg";
export { default as WAREHOUSE } from "../assets/images/warehouse.svg";
export { default as AIRPLANE } from "../assets/images/airplane.svg";
export { default as FRAME } from "../assets/images/frame.png";
export { default as FEND_IMPORT } from "../assets/images/fend-import.png";
export { default as CHECK_ROUND } from "../assets/images/check-round.svg";
export { default as CALL_FRAME } from "../assets/images/call-frame.svg";
export { default as FEND_FOOTER_LOGO } from "../assets/images/fend-footer.svg";
